YACASL2DIR= ../../../..
CASL2 = $(YACASL2DIR)/casl2
LIBDIR = $(YACASL2DIR)/as/casl2lib
MISCDIR = $(YACASL2DIR)/as/misc
ASFILE = divl.casl $(MISCDIR)/divl0.casl $(LIBDIR)/outl.casl
CMD = $(CASL2) $(ASFILE)
include $(YACASL2DIR)/test/TEST.mk
