include ../CMD.mk    # YACASL2DIR, CASL2
CASL2FLAG = -M640
ASDIR = $(YACASL2DIR)/as/FUNC
ASFILE = $(ASDIR)/mula_call.casl $(ASDIR)/mula2.casl $(ASDIR)/mull1.casl $(ASDIR)/outa.casl
CMD = $(CASL2) $(CASL2FLAG) $(ASFILE)
include ../TEST.mk
