YACASL2DIR= ../../../..
CASL2 = $(YACASL2DIR)/casl2
LIBDIR = $(YACASL2DIR)/as/casl2lib
APPDIR = $(YACASL2DIR)/as/app
ASFILE = count1.casl $(APPDIR)/count1.casl $(LIBDIR)/outa.casl
CMD = $(CASL2) $(ASFILE)
include $(YACASL2DIR)/test/TEST.mk
