include ../CMD.mk    # YACASL2DIR, CASL2
ASDIR = $(YACASL2DIR)/as/FUNC
ASFILE = $(ASDIR)/abs_call.casl $(ASDIR)/abs.casl $(ASDIR)/outa_main.casl $(ASDIR)/divl1.casl $(ASDIR)/rev.casl
include ../TEST.mk
