clean: clean_systemtest clean_unittest

clean_systemtest:
	@$(MAKE) -sC system/casl2 clean
	@$(MAKE) -sC system/comet2 clean
	@$(MAKE) -sC system/dumpword clean

clean_unittest:
	@$(MAKE) -sC unit clean
