include ../CMD.mk    # YACASL2DIR, CASL2
ASDIR = $(YACASL2DIR)/as/FUNC
ASFILE = $(ASDIR)/divl_call.casl $(ASDIR)/divl0.casl $(ASDIR)/outl_main.casl $(ASDIR)/rev.casl
CMD = $(CASL2) $(ASFILE)
include ../TEST.mk
