YACASL2DIR= ../../../..
CASL2 = $(YACASL2DIR)/casl2
MISCDIR = $(YACASL2DIR)/as/misc
ASFILE = $(MISCDIR)/io.casl
INFILE = teststr.txt
CMD = $(CASL2) $(ASFILE) <$(INFILE)
include $(YACASL2DIR)/test/TEST.mk
