include ../CMD.mk    # YACASL2DIR, CASL2
ASDIR = $(YACASL2DIR)/as/casl2lib_driver
LIBDIR = $(YACASL2DIR)/as/casl2lib
ASFILE = $(ASDIR)/abs_call.casl $(LIBDIR)/abs.casl $(LIBDIR)/outa.casl
CMD = $(CASL2) $(ASFILE)
include ../TEST.mk
