YACASL2DIR= ../../../../..
CASL2 = $(YACASL2DIR)/casl2
CASL2LIBDIR = $(YACASL2DIR)/as/casl2lib
ASFILE = testsummary.casl ../summary.casl
CMD = $(CASL2) $(ASFILE)
TESTDIR = $(YACASL2DIR)/test
include $(TESTDIR)/TEST.mk
