# -sLオプションで、1から10まで加算するopt.caslを実行
include ../CMD.mk               # YACASL2DIR, CASL2
include ../opt_s/CMD.mk         # ASDIR, ASFILE
CASL2FLAG = -sL
CMD = $(CASL2) $(CASL2FLAG) $(ASFILE)
include ../TEST.mk
