YACASL2DIR= ../../../..
CASL2 = $(YACASL2DIR)/casl2
CASL2LIBDIR = $(YACASL2DIR)/as/casl2lib
APPDIR = $(YACASL2DIR)/as/app
ASFILE = $(APPDIR)/fib_outl.casl $(CASL2LIBDIR)/outl.casl
CMD = $(CASL2) $(ASFILE)
include $(YACASL2DIR)/test/TEST.mk
