YACASL2DIR= ../../../../..
CASL2 = $(YACASL2DIR)/casl2
LIBDIR = $(YACASL2DIR)/as/casl2lib
ASFILE = addl32_0.casl $(LIBDIR)/addl32.casl
CMD = $(CASL2) $(ASFILE)
include $(YACASL2DIR)/test/integration/casl2/TEST.mk
