YACASL2DIR= ../../../..
CASL2 = $(YACASL2DIR)/casl2
LIBDIR = $(YACASL2DIR)/as/casl2lib
ASFILE = mull.casl $(LIBDIR)/mull.casl $(LIBDIR)/outl.casl
CMD = $(CASL2) $(ASFILE)
include $(YACASL2DIR)/test/integration/casl2/TEST.mk
