include ../CMD.mk    # YACASL2DIR, CASL2
CASL2FLAG = -sla
ASDIR = $(YACASL2DIR)/as/YAKUWA
ASFILE = $(ASDIR)/floatedit.casl
IN = <teststr.txt
CMD = $(CASL2) $(CASL2FLAG) $(ASFILE) $(IN)
include ../TEST.mk
