YACASL2DIR= ../../../../..
CASL2 = $(YACASL2DIR)/casl2
CASL2LIBDIR = $(YACASL2DIR)/as/casl2lib
ASFILE = test_ptn4.casl ../ptn4.casl ../ptn1.casl ../ptn2.casl $(CASL2LIBDIR)/outb.casl
CMD = $(CASL2) $(ASFILE)
include $(YACASL2DIR)/test/TEST.mk
