include ../CMD.mk    # YACASL2DIR, CASL2
CASL2FLAG = -aTd -M16
ASDIR = $(YACASL2DIR)/as
CASL2LIBDIR = $(YACASL2DIR)/as/casl2lib
ASFILE = $(YACASL2DIR)/as/cmd/JPL/jpl_o.casl
CMD = $(CASL2) $(CASL2FLAG) $(ASFILE)
include ../TEST.mk
