YACASL2DIR= ../../../..
CASL2 = $(YACASL2DIR)/casl2
LIBDIR = $(YACASL2DIR)/as/casl2lib
ASFILE = inl.casl $(LIBDIR)/inl.casl $(LIBDIR)/outl.casl
IN = teststr.txt
CMD = $(CASL2) $(ASFILE) <$(IN)
include $(YACASL2DIR)/test/TEST.mk
