include ../CMD.mk    # YACASL2DIR, CASL2
ASDIR = ../../../../as/FE_TESTS/2008_10/Q09
ASFUNCDIR = ../../../../as/FUNC
ASFILE = $(ASDIR)/ptn1_call.casl $(ASDIR)/ptn1.casl $(ASFUNCDIR)/outb.casl
CMD = $(CASL2) $(ASFILE)
include ../TEST.mk
