YACASL2DIR= ../../../../..
CASL2 = $(YACASL2DIR)/casl2
CASL2FLAG = -at -M160
CASL2LIBDIR = $(YACASL2DIR)/as/casl2lib
ASFILE = mula0.casl $(CASL2LIBDIR)/mula.casl
CMD = $(CASL2) $(CASL2FLAG) $(ASFILE)
include $(YACASL2DIR)/test/TEST.mk
