include ../CMD.mk    # YACASL2DIR, CASL2
LIBDIR = $(YACASL2DIR)/as/casl2lib
ASDIR = $(YACASL2DIR)/as/misc
ASFILE = $(ASDIR)/fib_outl.casl $(LIBDIR)/outl.casl
CMD = $(CASL2) $(ASFILE)
include ../TEST.mk
