include ../CMD.mk    # YACASL2DIR, CASL2
ASDIR = ../../../../as/FE_TESTS/2008_10/Q09
ASFUNCDIR = ../../../../as/FUNC
ASFILE = $(ASDIR)/ptn2_call.casl $(ASDIR)/ptn2.casl $(ASFUNCDIR)/outb.casl
include ../TEST.mk
