include ../CMD.mk    # YACASL2DIR, CASL2
CASL2FLAG = -atd -M8
ASDIR = $(YACASL2DIR)/as
CASL2LIBDIR = $(YACASL2DIR)/as/casl2lib
ASFILE = $(YACASL2DIR)/as/cmd/ADDA/adda0__z.casl
CMD = $(CASL2) $(CASL2FLAG) $(ASFILE)
include ../TEST.mk
