include ../CMD.mk    # YACASL2DIR, CASL2
CASL2FLAG = -M640
ASDIR = $(YACASL2DIR)/as/FUNC
ASFILE = $(ASDIR)/mula_call.casl $(ASDIR)/mula1.casl $(ASDIR)/outa.casl
COMET2FLAG = -M640
CMD = $(COMET2) $(COMET2FLAG) $(OBJFILE)
include ../TEST.mk
