include ../CMD.mk    # YACASL2DIR, CASL2
CASL2FLAG = -sla
ASDIR = $(YACASL2DIR)/as/FUNC
ASFILE = $(ASDIR)/abs_call.casl $(ASDIR)/abs.casl $(ASDIR)/outa.casl
CMD = $(CASL2) $(CASL2FLAG) $(ASFILE) $(IN)
include ../TEST.mk
