include ../CMD.mk    # YACASL2DIR, CASL2
ASDIR = $(YACASL2DIR)/as/casl2lib_test
LIBDIR = $(YACASL2DIR)/as/casl2lib
ASFILE = $(ASDIR)/minim_call.casl $(LIBDIR)/minim.casl $(LIBDIR)/outa.casl
CMD = $(CASL2) $(ASFILE)
include ../TEST.mk
