YACASL2DIR= ../../../..
CASL2 = $(YACASL2DIR)/casl2
LIBDIR = $(YACASL2DIR)/as/casl2lib
ASFILE = minim.casl $(LIBDIR)/minim.casl $(LIBDIR)/outa.casl
CMD = $(CASL2) $(ASFILE)
include $(YACASL2DIR)/test/TEST.mk
