include ../CMD.mk    # YACASL2DIR, CASL2
ASDIR = ../../../../as/FE_TESTS/2008_10/Q13
ASFILE = $(ASDIR)/summary_call.casl $(ASDIR)/summary.casl
CMD = $(CASL2) $(CASL2FLAG) $(ASFILE) $(IN)
include ../TEST.mk
