# -sLオプションで、1から10まで加算するsum_10.caslを実行
include ../CMD.mk               # YACASL2DIR, CASL2
include ../sum_10_s/CMD.mk      # ASDIR, ASFILE
CASL2FLAG = -sL
CMD = $(CASL2) $(CASL2FLAG) $(ASFILE)
include ../TEST.mk
