include ../CMD.mk    # YACASL2DIR, CASL2
CASL2FLAG = -sla
ASDIR = $(YACASL2DIR)/as/FUNC
ASFILE = $(ASDIR)/minim_call.casl $(ASDIR)/minim.casl $(ASDIR)/outa.casl 
CMD = $(CASL2) $(CASL2FLAG) $(ASFILE) $(IN)
include ../TEST.mk
