YACASL2DIR= ../../../..
CASL2 = $(YACASL2DIR)/casl2
LIBDIR = $(YACASL2DIR)/as/casl2lib
ASFILE = addl32_1.casl $(LIBDIR)/addl32.casl $(LIBDIR)/outl.casl
CMD = $(CASL2) $(ASFILE)
include $(YACASL2DIR)/test/TEST.mk
