include ../CMD.mk    # YACASL2DIR, CASL2
LIBDIR = $(YACASL2DIR)/as/casl2lib
ASDIR = $(YACASL2DIR)/as/casl2lib_test
ASFILE = $(ASDIR)/divl_call.casl $(LIBDIR)/divl.casl $(LIBDIR)/outl_main.casl $(LIBDIR)/rev.casl
CMD = $(CASL2) $(ASFILE)
include ../TEST.mk
