include ../CMD.mk    # YACASL2DIR, CASL2
ASDIR = $(YACASL2DIR)/as
CASL2LIBDIR = $(YACASL2DIR)/as/casl2lib
ASFILE = $(YACASL2DIR)/as/err/err_106_DS.casl
CMD = $(CASL2) $(CASL2FLAG) $(ASFILE)
include ../TEST.mk
