YACASL2DIR= ../../../..
CASL2 = $(YACASL2DIR)/casl2
LIBDIR = $(YACASL2DIR)/as/casl2lib
ASFILE = divl.casl $(LIBDIR)/outl.casl    # DIVLは、outl.caslに含まれる
CMD = $(CASL2) $(ASFILE)
include $(YACASL2DIR)/test/TEST.mk
