include ../CMD.mk    # YACASL2DIR, CASL2
CASL2FLAG = -atd -M16
ASDIR = $(YACASL2DIR)/as
CASL2LIBDIR = $(YACASL2DIR)/as/casl2lib
ASFILE = $(YACASL2DIR)/as/cmd/JOV/jov_m.casl
CMD = $(CASL2) $(CASL2FLAG) $(ASFILE)
include ../TEST.mk
